### ISSUE TITLE
/cptl start doesn't work with coreprotect 22.4

### ISSUE THREAD

**Issue by PF94** [R2bEEaton-Minecraft/CoreProtectTimeLapse#9]
```
[04:07:08] [Server thread/INFO]: LiquidEzra issued server command: /cptl start 512 1711166027 1715917515 300 ~ ~ ~
[04:07:08] [Thread-32/WARN]: Exception in thread "Thread-32" java.lang.NoClassDefFoundError: net/coreprotect/database/Rollback
[04:07:08] [Thread-32/WARN]: 	at CoreProtectTimeLapse-v1.0.3-all.jar//cc.spea.CoreProtectTimeLapse.FakeCoreProtectAPI.processData(FakeCoreProtectAPI.java:145)
[04:07:08] [Thread-32/WARN]: 	at CoreProtectTimeLapse-v1.0.3-all.jar//cc.spea.CoreProtectTimeLapse.FakeCoreProtectAPI.performRollback(FakeCoreProtectAPI.java:20)
[04:07:08] [Thread-32/WARN]: 	at CoreProtectTimeLapse-v1.0.3-all.jar//cc.spea.CoreProtectTimeLapse.CommandManager.lambda$registerAll$1(CommandManager.java:94)
[04:07:08] [Thread-32/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[04:07:08] [Thread-32/WARN]: Caused by: java.lang.ClassNotFoundException: net.coreprotect.database.Rollback
[04:07:08] [Thread-32/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[04:07:08] [Thread-32/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[04:07:08] [Thread-32/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[04:07:08] [Thread-32/WARN]: 	... 4 more
```

i don't know why this happens. i have coreprotect 22.4 installed on a papermc 1.20.4 server.

is this a database-related issue? my coreprotect is configured to use a mysql database.

EDIT: this is caused by a breaking change on 22.4 in commit https://github.com/PlayPro/CoreProtect/commit/dc87d4fbf474130c2ef04ba7a450ad08942b57ac
